-- CREATE TABLE koalas (
--     id serial PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     gender VARCHAR(200) NOT NULL,
--     age VARCHAR(20) NOT NULL,
--     transfer_status VARCHAR(20) NOT NULL,
--     notes VARCHAR(200) NOT NULL
--     );
    
--  INSERT INTO koalas (name, gender, age, transfer_status, notes)
--  VALUES ('Scotty', 'M', 4, 'Y', 'Born in Guatemala'),
-- ('Jean', 'F', 5, 'Y', 'Allergic to lots of lava'),
-- ('Ororo', 'F', 7, 'N', 'loves listening to Paula (Abdul)'),
-- ('Logan', 'M', 15, 'N', 'Love the sauna'),
-- ('Charlie', 'M', 9, 'Y', 'Favorite band is Nirvana'),
-- ('Betsy', 'F', 4, 'Y', 'Has a pet iguana');